In [0]:
from google.colab import files

In [6]:
files.upload()

Saving car.data to car.data


{'car.data': b'vhigh,vhigh,2,2,small,low,unacc\nvhigh,vhigh,2,2,small,med,unacc\nvhigh,vhigh,2,2,small,high,unacc\nvhigh,vhigh,2,2,med,low,unacc\nvhigh,vhigh,2,2,med,med,unacc\nvhigh,vhigh,2,2,med,high,unacc\nvhigh,vhigh,2,2,big,low,unacc\nvhigh,vhigh,2,2,big,med,unacc\nvhigh,vhigh,2,2,big,high,unacc\nvhigh,vhigh,2,4,small,low,unacc\nvhigh,vhigh,2,4,small,med,unacc\nvhigh,vhigh,2,4,small,high,unacc\nvhigh,vhigh,2,4,med,low,unacc\nvhigh,vhigh,2,4,med,med,unacc\nvhigh,vhigh,2,4,med,high,unacc\nvhigh,vhigh,2,4,big,low,unacc\nvhigh,vhigh,2,4,big,med,unacc\nvhigh,vhigh,2,4,big,high,unacc\nvhigh,vhigh,2,more,small,low,unacc\nvhigh,vhigh,2,more,small,med,unacc\nvhigh,vhigh,2,more,small,high,unacc\nvhigh,vhigh,2,more,med,low,unacc\nvhigh,vhigh,2,more,med,med,unacc\nvhigh,vhigh,2,more,med,high,unacc\nvhigh,vhigh,2,more,big,low,unacc\nvhigh,vhigh,2,more,big,med,unacc\nvhigh,vhigh,2,more,big,high,unacc\nvhigh,vhigh,3,2,small,low,unacc\nvhigh,vhigh,3,2,small,med,unacc\nvhigh,vhigh,3,2,small,high,u

In [0]:
import os

In [8]:
os.listdir()

['.config', 'car.data', 'sample_data']

#### PREPROCESSING

In [0]:
import pandas as pd

In [10]:
data=pd.read_csv('car.data')
data

vhigh vhigh.1      2   2.1  small   low  unacc
0     vhigh   vhigh      2     2  small   med  unacc
1     vhigh   vhigh      2     2  small  high  unacc
2     vhigh   vhigh      2     2    med   low  unacc
3     vhigh   vhigh      2     2    med   med  unacc
4     vhigh   vhigh      2     2    med  high  unacc
5     vhigh   vhigh      2     2    big   low  unacc
6     vhigh   vhigh      2     2    big   med  unacc
7     vhigh   vhigh      2     2    big  high  unacc
8     vhigh   vhigh      2     4  small   low  unacc
9     vhigh   vhigh      2     4  small   med  unacc
10    vhigh   vhigh      2     4  small  high  unacc
11    vhigh   vhigh      2     4    med   low  unacc
12    vhigh   vhigh      2     4    med   med  unacc
13    vhigh   vhigh      2     4    med  high  unacc
14    vhigh   vhigh      2     4    big   low  unacc
15    vhigh   vhigh      2     4    big   med  unacc
16    vhigh   vhigh      2     4    big  high  unacc
17    vhigh   vhigh      2  more  small   low  unacc
18    vhigh   vhigh      2  more  small   med  unacc
19    vhigh   vhigh      2  more  small  high  unacc
20    vhigh   vhigh      2  more    med   low  unacc
21    vhigh   vhigh      2  more    med   med  unacc
22    vhigh   vhigh      2  more    med  high  unacc
23    vhigh   vhigh      2  more    big   low  unacc
24    vhigh   vhigh      2  more    big   med  unacc
25    vhigh   vhigh      2  more    big  high  unacc
26    vhigh   vhigh      3     2  small   low  unacc
27    vhigh   vhigh      3     2  small   med  unacc
28    vhigh   vhigh      3     2  small  high  unacc
29    vhigh   vhigh      3     2    med   low  unacc
...     ...     ...    ...   ...    ...   ...    ...
1697    low     low      4  more    big   low  unacc
1698    low     low      4  more    big   med   good
1699    low     low      4  more    big  high  vgood
1700    low     low  5more     2  small   low  unacc
1701    low     low  5more     2  small   med  unacc
1702    low     low  5more     2  small  high  unacc
1703    low     low  5more     2    med   low  unacc
1704    low     low  5more     2    med   med  unacc
1705    low     low  5more     2    med  high  unacc
1706    low     low  5more     2    big   low  unacc
1707    low     low  5more     2    big   med  unacc
1708    low     low  5more     2    big  high  unacc
1709    low     low  5more     4  small   low  unacc
1710    low     low  5more     4  small   med    acc
1711    low     low  5more     4  small  high   good
1712    low     low  5more     4    med   low  unacc
1713    low     low  5more     4    med   med   good
1714    low     low  5more     4    med  high  vgood
1715    low     low  5more     4    big   low  unacc
1716    low     low  5more     4    big   med   good
1717    low     low  5more     4    big  high  vgood
1718    low     low  5more  more  small   low  unacc
1719    low     low  5more  more  small   med    acc
1720    low     low  5more  more  small  high   good
1721    low     low  5more  more    med   low  unacc
1722    low     low  5more  more    med   med   good
1723    low     low  5more  more    med  high  vgood
1724    low     low  5more  more    big   low  unacc
1725    low     low  5more  more    big   med   good
1726    low     low  5more  more    big  high  vgood

[1727 rows x 7 columns]

In [0]:
from sklearn.preprocessing import LabelEncoder

In [12]:
data.shape

(1727, 7)

In [13]:
type(data)

pandas.core.frame.DataFrame

In [0]:
labels=data.iloc[:,-1].values

In [15]:
labels

array(['unacc', 'unacc', 'unacc', ..., 'unacc', 'good', 'vgood'],
      dtype=object)

In [0]:
xdata = data.iloc[:,:-1].values

In [17]:
xdata

array([['vhigh', 'vhigh', '2', '2', 'small', 'med'],
       ['vhigh', 'vhigh', '2', '2', 'small', 'high'],
       ['vhigh', 'vhigh', '2', '2', 'med', 'low'],
       ...,
       ['low', 'low', '5more', 'more', 'big', 'low'],
       ['low', 'low', '5more', 'more', 'big', 'med'],
       ['low', 'low', '5more', 'more', 'big', 'high']], dtype=object)

In [18]:
labels.shape, xdata.shape

((1727,), (1727, 6))

In [0]:
enc = LabelEncoder()


In [0]:
enc_labels = enc.fit(labels).fit_transform(labels)

In [22]:
enc_labels

array([2, 2, 2, ..., 2, 1, 3])

In [0]:
from keras.utils import to_categorical

In [0]:
hot_enc_labels=to_categorical(enc_labels)

In [34]:
hot_enc_labels

array([[0., 0., 1., 0.],
       [0., 0., 1., 0.],
       [0., 0., 1., 0.],
       ...,
       [0., 0., 1., 0.],
       [0., 1., 0., 0.],
       [0., 0., 0., 1.]], dtype=float32)

In [40]:
enc_xdata = enc.fit(xdata)

ValueError: ignored

array([['vhigh', 'vhigh', '2', '2', 'small', 'med'],
       ['vhigh', 'vhigh', '2', '2', 'small', 'high'],
       ['vhigh', 'vhigh', '2', '2', 'med', 'low'],
       ...,
       ['low', 'low', '5more', 'more', 'big', 'low'],
       ['low', 'low', '5more', 'more', 'big', 'med'],
       ['low', 'low', '5more', 'more', 'big', 'high']], dtype=object)

In [0]:
new_data=pd.DataFrame(xdata)

In [0]:
new_data=new_data.apply(LabelEncoder().fit_transform)

In [54]:
type(new_data)

pandas.core.frame.DataFrame

In [0]:
import numpy as np

In [0]:
numpy_xlabel = np.asarray(new_data)

In [57]:
numpy_xlabel.shape

(1727, 6)

In [58]:
numpy_xlabel.shape,hot_enc_labels.shape

((1727, 6), (1727, 4))

In [0]:
numpy_xlabel = numpy_xlabel/4
numpy_xlabel =numpy_xlabel.astype(np.float32)

In [62]:
numpy_xlabel

array([[0.1875, 0.1875, 0.    , 0.    , 0.125 , 0.125 ],
       [0.1875, 0.1875, 0.    , 0.    , 0.125 , 0.    ],
       [0.1875, 0.1875, 0.    , 0.    , 0.0625, 0.0625],
       ...,
       [0.0625, 0.0625, 0.1875, 0.125 , 0.    , 0.0625],
       [0.0625, 0.0625, 0.1875, 0.125 , 0.    , 0.125 ],
       [0.0625, 0.0625, 0.1875, 0.125 , 0.    , 0.    ]], dtype=float32)

In [0]:
from sklearn.model_selection import train_test_split

In [0]:
xtrain,xtest,ytrain,ytest = train_test_split(numpy_xlabel,hot_enc_labels,test_size=0.3,random_state=7)

### BUILDING THE NETWORK

In [67]:
from keras import layers
from keras import models

6

In [0]:
network = models.Sequential()
network.add(layers.Dense(64,activation='relu',input_shape=(xtrain.shape[1],)))
network.add(layers.Dense(64,activation='relu',input_shape=(xtrain.shape[1],)))
network.add(layers.Dense(4,activation='sigmoid'))
network.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])

In [74]:
network.fit(xtrain,ytrain,epochs=300,batch_size=100)

Epoch 1/300
1208/1208 [==============================] - 0s 186us/step - loss: 1.3583 - acc: 0.5662
Epoch 2/300
1208/1208 [==============================] - 0s 18us/step - loss: 1.2790 - acc: 0.6945
Epoch 3/300
1208/1208 [==============================] - 0s 17us/step - loss: 1.1503 - acc: 0.6945
Epoch 4/300
1208/1208 [==============================] - 0s 19us/step - loss: 0.9865 - acc: 0.6945
Epoch 5/300
1208/1208 [==============================] - 0s 19us/step - loss: 0.8646 - acc: 0.6945
Epoch 6/300
1208/1208 [==============================] - 0s 19us/step - loss: 0.8369 - acc: 0.6945
Epoch 7/300
1208/1208 [==============================] - 0s 17us/step - loss: 0.8354 - acc: 0.6945
Epoch 8/300
1208/1208 [==============================] - 0s 24us/step - loss: 0.8310 - acc: 0.6945
Epoch 9/300
1208/1208 [==============================] - 0s 19us/step - loss: 0.8270 - acc: 0.6945
Epoch 10/300
1208/1208 [==============================] - 0s 17us/step - loss: 0.8235 - acc: 0.6945
Epoch 11

In [75]:
network.evaluate(xtest,ytest)

519/519 [==============================] - 0s 113us/step


[0.11938316442488706, 0.9691714836223507]